- Dockerfile
- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> Sync with luigibk head repo changes

- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> making the app's metrics available for prometheus scraping

- exim.conf
- helm/exim/templates/statefulsetOrdeployment.yaml
> DTSPO-1477 enable tls and update helm chart for secret

- helm/exim/templates/statefulsetOrdeployment.yaml
> indentation

- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> changes to add customised exim-exporter

- helm/exim/templates/statefulsetOrdeployment.yaml
Fix for Helm release errors on dev
> mountpath fix for pvc

- helm/exim/templates/statefulsetOrdeployment.yaml
> DTSPO-1425 fix for the missing pvc mountpath errors

- Dockerfile
based on the response for the issue raised under - https://github.com/gvengel/exim_exporter/issues/7
```
[ ] Yes
[ ] No
```
> Fixing exim container initialisation issues

- helm/exim/templates/eximexporter-service.yaml
- helm/exim/values.yaml
> Dtspo-1425 service monitor setup for prometheus

- helm/exim/templates/eximexporter-service.yaml
- helm/exim/values.yaml
> Fixing the helm chart template issues

- helm/exim/templates/eximexporter-service.yaml
> fixing service naming conflict issues

- helm/exim/templates/statefulsetOrdeployment.yaml
> fix broken dev deployment

- helm/exim/templates/statefulsetOrdeployment.yaml
based on https://github.com/gvengel/exim_exporter/issues/8
```
[ ] Yes
[ ] No
```
> fix metrics readability from exim container

- exim.conf
- helm/exim/templates/statefulsetOrdeployment.yaml
> DTSPO-1477 add separate cert files to helm and config

- helm/exim/templates/statefulsetOrdeployment.yaml
https://github.com/gvengel/exim_exporter/issues/8#issuecomment-846633170
```
[ ] Yes
[ ] No
```
> DTSPO-1425 Change to stateful

- exim.conf
- helm/exim/templates/statefulsetOrdeployment.yaml
> create subdirectory for default outbound cert

- helm/exim/templates/statefulsetOrdeployment.yaml
> DTSPO-1425 new env variables

- README.md
> README notes about certificates

- exim.conf
- helm/exim/templates/service.yaml
- helm/exim/values.yaml
Using 587 as a standard for starttls
use 8587, expose as 587
```
[ ] Yes
[ ] No
```
> Dtspo 2915 8587 port

- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> DTSPO-1425 exim exporter updates

- exim.conf
- helm/exim/templates/authSecretProviderClass.yaml
- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> DTSPO-2912 smtp auth + csi driver secrets

- helm/exim/templates/authSecretProviderClass.yaml
- helm/exim/values.yaml
> DTSPO-2192 smtp auth fixes

- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> DTSPO-3352 Add internalTls config

- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> Load external inbound tls cert + key

- README.md
- helm/exim/templates/authCertificateProviderClass.yaml
- helm/exim/templates/statefulsetOrdeployment.yaml
- helm/exim/values.yaml
> Dtspo 3353

- helm/exim/templates/statefulsetOrdeployment.yaml
https://tools.hmcts.net/jira/browse/DTSPO-3353
Updating configuration file to specify mouth path. 
```
[ ] Yes
[x] No
```
> DTSPO-3353: update exim-relay configuration

- helm/exim/templates/authCertificateProviderClass.yaml
> DTSPO-3353 changed secret provider class to seperate cert

- helm/exim/templates/authCertificateProviderClass.yaml
- helm/exim/values.yaml
> DTSPO 3533 added object alias

- helm/exim/templates/statefulsetOrdeployment.yaml
> edited statefulset object paths

- helm/exim/templates/outboundCertificateProviderClass.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4398
Updated the file name for key file to match expected value
```
[ ] Yes
[x] No
```
> DTSPO-4398: Update cert key filename

- helm/exim/templates/outboundCertificateProviderClass.yaml
https://tools.hmcts.net/jira/browse/DTSPO-4398
Updated typo in file name
```
[ ] Yes
[x] No
```
> DTSPO-4398: Update cert key filename typo

- helm/exim/templates/outboundCertificateProviderClass.yaml
work in progress, trying to fix certificate error. 
```
[ ] Yes
[ ] No
```
> changed outbound cert

- helm/exim/templates/outboundCertificateProviderClass.yaml
reverted last change, back to outbound certs. 
```
[ ] Yes
[ ] No
```
> reverting to outbound certs

- README.md
- helm/exim/values.yaml
https://tools.hmcts.net/jira/browse/DTSPO-8561
Updates to configuration for inbound and outbound certs
```
[ ] Yes
[ ] No
```
> Dtspo 8561 migrate from sops 2

- helm/exim/templates/envSecretsProviderClass.yaml
Updating config file structure to fix helm chart build errors in cluster
```
[ ] Yes
[ ] No
```
> DTSPO-9393: Updated csi file structure

- helm/exim/templates/envSecretsProviderClass.yaml
Minor changes to config
```
[ ] Yes
[ ] No
```
> DTSPO-9393: update config csi file 2

- exim.conf
https://tools.hmcts.net/jira/browse/DTSPO-8561
Updating configuration. Following documentation that provides some example of configuring exim.
```
[ ] Yes
[ ] No
```
> DTSPO-8561: Update configuration

- exim.conf
Fixing error:
`Exim configuration error for smarthost router:
route_list or route_data (but not both) must be specified`
```
[ ] Yes
[ ] No
```
> DTSPO-8561: Fix update to config

- exim.conf
Reverting change to exim configuration
```
[ ] Yes
[ ] No
```
> DTSPO-8561 update configuration fix revert

- azure_pipeline.yaml
- helm/exim/templates/authSecretProviderClass.yaml
- helm/exim/templates/envSecretsProviderClass.yaml
- helm/exim/templates/inboundCertificateProviderClass.yaml
- helm/exim/templates/outboundCertificateProviderClass.yaml
- helm/exim/templates/statefulsetOrdeployment.yaml
DTSPO-12677
Add WI to mailrelay
> Add WI mailrelay

- helm/exim/values.yaml
> Revert "Dtspo 12677"
